#!/usr/bin/env bash
# Registers the native messaging helper so the extension can launch mpv (Linux and macOS).
# Keep this compatible with macOS's bash 3.2: no associative arrays, no readlink -f.
set -euo pipefail

HOST_NAME="local.play_in_mpv"
EXTENSION_ID="coiofchhcnfpogppabiheboajgpmhcki"  # fixed by the "key" in extension/manifest.json
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_PY="$DIR/play_in_mpv_host.py"
RESTART_HINT="restart the browser"

case "$(uname)" in
  Darwin)
    SUPPORT="$HOME/Library/Application Support"
    BROWSER_DIRS=(
      "$SUPPORT/BraveSoftware/Brave-Browser"
      "$SUPPORT/Google/Chrome"
      "$SUPPORT/Chromium"
    )
    MPV_HINT="brew install mpv"
    RESTART_HINT="fully quit the browser (Cmd+Q) and relaunch it from the Dock"

    # A browser launched from the Dock gets PATH=/usr/bin:/bin:/usr/sbin:/sbin, so the
    # manifest points at a generated wrapper that runs a working python3 by absolute path.
    PYTHON=""
    for py in /opt/homebrew/bin/python3 /usr/local/bin/python3 "$(command -v python3 || true)"; do
      [ -n "$py" ] && [ -x "$py" ] || continue
      # Apple's /usr/bin/python3 is a stub that pops an install dialog and fails unless the
      # Command Line Tools are installed.
      if [ "$py" = /usr/bin/python3 ] && ! xcode-select -p >/dev/null 2>&1; then
        continue
      fi
      if "$py" -c 'import sys; sys.exit(sys.version_info < (3,))' >/dev/null 2>&1; then
        PYTHON="$py"
        break
      fi
    done
    if [ -z "$PYTHON" ]; then
      echo "error: no working Python 3 found — install it with: brew install python" >&2
      exit 1
    fi

    HOST_PATH="$DIR/play_in_mpv_host_macos.sh"
    cat > "$HOST_PATH" <<WRAPPER
#!/bin/sh
# Generated by install.sh — re-run it if you move the repo or change Python.
exec "$PYTHON" "$HOST_PY" "\$@"
WRAPPER
    chmod +x "$HOST_PATH"
    echo "Using Python: $PYTHON"
    ;;
  *)
    BROWSER_DIRS=(
      "$HOME/.config/BraveSoftware/Brave-Browser"
      "$HOME/.config/google-chrome"
      "$HOME/.config/chromium"
    )
    MPV_HINT="sudo apt install mpv"
    HOST_PATH="$HOST_PY"
    ;;
esac

command -v mpv >/dev/null || echo "warning: mpv not found — install it with: $MPV_HINT"
chmod +x "$HOST_PY"

installed=0
for browser_dir in "${BROWSER_DIRS[@]}"; do
  [ -d "$browser_dir" ] || continue
  mkdir -p "$browser_dir/NativeMessagingHosts"
  cat > "$browser_dir/NativeMessagingHosts/$HOST_NAME.json" <<EOF2
{
  "name": "$HOST_NAME",
  "description": "Launch mpv for Play in mpv extension",
  "path": "$HOST_PATH",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXTENSION_ID/"]
}
EOF2
  echo "Registered helper for $browser_dir"
  installed=1
done

[ "$installed" = 1 ] || { echo "No Brave/Chrome/Chromium profile found."; exit 1; }
echo "Now load $DIR/extension via chrome://extensions → Developer mode → Load unpacked, then $RESTART_HINT."
